server:
  port: 8002
databases:
  - user: admin-1
    password: admin
    host: localhost
    dbName: shop
  - user: admin-2
    password: admin
    host: localhost
    dbName: order
security:
  jwt:
    key: abcxyz