server:
  port: 8002
postgres: 
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres
  dbname: movietheater
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
security:
  jwt:
    key: abcxyz